name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8.15.4 # Specify the pnpm version you're using
      - uses: actions/setup-node@v4
        with:
          node-version: 20 # Use a recent Node.js version
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm build
